bulk_indexer: Remove ES field mapper field preview
elastic/go-docappender pull request #190
Opened 2024-07-26 12:18 UTC by kruskall

Removes the field mapper exception field preview returned in the error reason by Elasticsearch.

2024-07-26 13:36 UTC, carsonip commented on bulk_indexer.go
> +											item.Error.Reason, ": enable `JsonReadFeature.ALLOW_NON_NUMERIC_NUMBERS` to allow",
This seems very targeted. WDYT about just removing reason when error.type is `x_content_parse_exception`?

2024-07-26 21:38 UTC, 1pkg submitted a review, later dismissed

2024-07-29 07:59 UTC, simitt requested changes
++ on Carson's comment in https://github.com/elastic/go-docappender/pull/190#discussion_r1693073045

2024-07-29 08:27 UTC, carsonip reviewed
I'm still investigating the 2 different "types" / "reason" of error under x_content_parse_exception. Let's keep this PR open until we have a better idea of what's happening.

2024-07-29 11:07 UTC, carsonip commented on bulk_indexer.go
> +						// For unavailable_shards_exception, remove item.Error.Reason
nit: wrong comment.
nit: this if statement can be merged into the previous if statement for simplicity
```suggestion
						// For x_content_parse_exception, remove item.Error.Reason
```

2024-07-29 15:50 UTC, carsonip approved these changes
lgtm, thanks

2024-07-29 15:55 UTC, merged